package PR108;
import java.util.ArrayList;
public class Solution {
    public static void main(String[] args) throws Exception {//Тут с 1 по 5 
        try {
            int a = 33 / 0;
        } catch (ArithmeticException ae) {
            System.out.println("ArithmeticException");
        }
        try {
            String s = null;
            String m = s.toLowerCase();
        } catch (NullPointerException npe) {
            System.out.println("NullPointerException");
        }
        try {
            int[] m = new int[2];
            m[8] = 5;
        } catch (ArrayIndexOutOfBoundsException aioobe) {
            System.out.println("ArrayIndexOutOfBoundsException");
        }
        try {
            ArrayList<String> list = new ArrayList<String>();
            String s = list.get(18);
        } catch (IndexOutOfBoundsException ioobe) {
            System.out.println("IndexOutOfBoundsException");
        }
        try {
            method1();
        } catch (Exception1 e) {
        }
    }
    public static void method1() throws Exception1, Exception2, Exception3
    {
        int i = (int) (Math.random() * 3);
        if (i == 0)
            throw new Exception1();
        if (i == 1)
            throw new Exception2();
        if (i == 2)
            throw new Exception3();
    }
}
class Exception1 extends Exception {
}
class Exception2 extends Exception1 {
}
class Exception3 extends Exception2 {
}


